


pool:
  vmImage: ubuntu-latest
variables:
  acrserviceconnection: 'acr-connection'
  frontendrepository: 'credpay/frontend'
  userrepository: 'credpay/user-service'
  paymentrepository: 'credpay/payment-service'
  tag: '$(Build.BuildId)'
stages:
  - stage: dockerbuild
    displayName: docker build
    jobs:
      - job: buildpushimages
        steps:
          - checkout: self
          - task: Docker@2
            displayName: frontend
            inputs:
              containerRegistry: 'acr-connection'
              repository: '$(frontendrepository)'
              command: 'buildAndPush'
              Dockerfile: 'frontend-react/dockerfile'
              buildContext: 'frontend-react'
              tags: |
                $(tag)
                latest
          - task: Docker@2
            displayName: userrepo
            inputs:
              containerRegistry: 'acr-connection'
              repository: '$(userrepository)'
              command: 'buildAndPush'
              Dockerfile: 'userrepository/dockerfile'
              buildContext: 'user-service'
              tags: |
                $(tag)
                latest
          - task: Docker@2
            displayName: payment
            inputs:
              containerRegistry: 'acr-connection'
              repository: 'acr-connection'
              command: 'buildAndPush'
              Dockerfile: 'paymentrepository/dockerfile'
              buildContext: 'payment-service'
              tags: |
                $(tag)
                latest

    



